# Generated by Django 2.2.6 on 2019-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('createdate', models.DateField(auto_created=True, verbose_name='创建时间')),
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=30, verbose_name='账号')),
                ('cp_title', models.CharField(max_length=30, verbose_name='公司名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('cp_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('cp_tel', models.CharField(max_length=20, verbose_name='电话')),
                ('cp_address', models.CharField(max_length=80, verbose_name='地址')),
                ('cp_about', models.CharField(max_length=100, verbose_name='自我介绍')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('createdate', models.DateField(auto_created=True, verbose_name='发布时间')),
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=30, verbose_name='公司名')),
                ('cp_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('cp_tel', models.CharField(max_length=20, verbose_name='电话')),
                ('cp_address', models.CharField(max_length=80, verbose_name='地址')),
                ('cp_about', models.CharField(max_length=100, verbose_name='自我介绍')),
                ('info', models.TextField(verbose_name='招聘内容')),
                ('info_img', models.CharField(default='', max_length=256, verbose_name='图片')),
            ],
            options={
                'db_table': 'Info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, verbose_name='账号')),
                ('user_title', models.CharField(max_length=30, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, verbose_name='性别')),
                ('user_tel', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(max_length=80, verbose_name='地址')),
                ('user_about', models.CharField(max_length=100, verbose_name='自我介绍')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ManyToManyField(to='testapp.Company')),
                ('info', models.ManyToManyField(to='testapp.Information')),
                ('user', models.ManyToManyField(to='testapp.User')),
            ],
            options={
                'db_table': 'Relationship',
            },
        ),
    ]
