# Generated by Django 2.2.6 on 2019-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('com_time', models.DateField(auto_created=True, verbose_name='发布时间')),
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_about', models.CharField(max_length=30, verbose_name='内容')),
            ],
            options={
                'db_table': 'Com',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='classes',
            field=models.CharField(choices=[('it', '计算机'), ('service', '服务业'), ('financial', '金融'), ('realty', '房地产'), ('medical', '医疗'), ('education', '教育')], default='', max_length=20, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='information',
            name='job',
            field=models.CharField(default='网络工程师', max_length=20, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='com',
            field=models.ManyToManyField(to='testapp.Comments'),
        ),
    ]
