# Generated by Django 2.2.6 on 2019-12-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20191204_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
