# Generated by Django 2.2.6 on 2019-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20191204_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
