# Generated by Django 2.2.6 on 2019-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20191206_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cp_about',
            field=models.CharField(max_length=100, verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_about',
            field=models.CharField(max_length=100, verbose_name='自我介绍'),
        ),
    ]
