# Generated by Django 2.2.6 on 2019-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20191206_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='com_time',
            field=models.DateField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='company',
            name='createdate',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='createdate',
            field=models.DateField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
