# Generated by Django 2.2.6 on 2019-12-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20191206_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='info_img',
        ),
    ]
