# Generated by Django 2.2.6 on 2019-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_remove_information_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='info_img',
            field=models.ImageField(default='', max_length=256, upload_to='', verbose_name='图片'),
        ),
    ]
