# Generated by Django 2.2.6 on 2019-12-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_information_info_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='cp_about',
        ),
    ]
