# Generated by Django 2.2.6 on 2019-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_information_cp_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='cp_name',
            new_name='cp_title',
        ),
    ]
