# Generated by Django 2.2.6 on 2019-12-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20191206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info_img',
            field=models.ImageField(default='', max_length=256, upload_to='img', verbose_name='图片'),
        ),
    ]
