# Generated by Django 2.2.6 on 2019-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20191207_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cp_title',
            field=models.CharField(default='', max_length=30, verbose_name='公司名'),
        ),
        migrations.AddField(
            model_name='collection',
            name='job',
            field=models.CharField(default='', max_length=20, verbose_name='职位'),
        ),
    ]
