# Generated by Django 2.2.6 on 2019-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20191207_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_collection',
            name='cp_id',
        ),
        migrations.RemoveField(
            model_name='c_collection',
            name='userid',
        ),
        migrations.AddField(
            model_name='c_collection',
            name='cp_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='c_collection',
            name='job',
            field=models.CharField(default='', max_length=20, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='c_collection',
            name='user_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='information',
            name='classes',
            field=models.CharField(choices=[('it', '计算机'), ('service', '服务业'), ('financial', '金融'), ('realty', '房地产'), ('medical', '医疗'), ('education', '教育')], max_length=20, verbose_name='类别'),
        ),
    ]
