# Generated by Django 2.2.6 on 2019-12-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20191207_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='info_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
