# Generated by Django 2.2.6 on 2019-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_comments_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_collection',
            name='cp_name',
        ),
        migrations.AddField(
            model_name='c_collection',
            name='cp_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
