# Generated by Django 2.2.6 on 2019-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20191207_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_collection',
            name='info_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
