# Generated by Django 2.2.6 on 2020-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_comments_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info_img',
            field=models.ImageField(max_length=256, upload_to='img', verbose_name='图片'),
        ),
    ]
