# Generated by Django 2.2.6 on 2020-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_auto_20200207_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
