# Generated by Django 2.2.6 on 2020-02-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_information_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
