# Generated by Django 2.2.6 on 2020-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_auto_20200211_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_collection',
            name='is_look',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='已查看'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
