# Generated by Django 2.2.6 on 2020-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_auto_20200212_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cp_img',
            field=models.ImageField(default='img/default.png', max_length=256, upload_to='img', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='img/default.png', max_length=256, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='c_collection',
            name='is_look',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='已查看'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
