# Generated by Django 2.2.10 on 2020-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_auto_20200212_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c_collection',
            options={'verbose_name': '简历'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '招聘信息'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': '关联'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterField(
            model_name='c_collection',
            name='is_look',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='已查看'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
