# Generated by Django 2.2.10 on 2020-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_auto_20200213_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_collection',
            name='pay',
            field=models.CharField(default='3000-5000', max_length=50, verbose_name='薪酬'),
        ),
        migrations.AddField(
            model_name='collection',
            name='pay',
            field=models.CharField(default='3000-5000', max_length=50, verbose_name='薪酬'),
        ),
        migrations.AddField(
            model_name='comments',
            name='pay',
            field=models.CharField(default='3000-5000', max_length=50, verbose_name='薪酬'),
        ),
        migrations.AlterField(
            model_name='information',
            name='pay',
            field=models.CharField(default='3000-5000', max_length=50, verbose_name='薪酬'),
        ),
    ]
