# Generated by Django 2.2.10 on 2020-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_auto_20200216_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_collection',
            name='is_look',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='已查看'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_hot',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10, verbose_name='首页轮播'),
        ),
    ]
